### ISSUE TITLE
Is C++14 allowed

### ISSUE THREAD

**Issue by nikonikolov** [LangProc/langproc_2015_cw#10]
Are we allowed to use c++14?

**Comment by m8pple** [comment]
I think that comes down to what the C++ compiler in the lab ubuntu setup supports. As long
as it supports -std=c++14 and/or supports the language features you want to use, then
feel free to enable it in your makefile.

**Comment by tomhartley** [comment]
I've tested: -std=c++1y is supported, -std=c++14 is not. It's a GCC version from 2013 so i don't think the standard was finalised, but some features might be (potentially buggy) supported through c++1y.
