### ISSUE TITLE
MIPS 4 Testing

### ISSUE THREAD

**Issue by adityarajagopal** [LangProc/langproc_2015_cw#12]
While running codegen on lab computers, I noticed that by default qemu runs mips1. Some of us use mips 4 instructions (movn and movz). Since the specs don't mention the version of MIPS to run in, just wanted to make sure that qemu will be called with the -mips4 or above flag.

**Comment by m8pple** [comment]
Hrmm - ok, this is an error of under-specification on my part. I intended MIPS1, but really there
is no particular reason to restrict it to that.

So yes - I'll make sure it is running under MIPS4 for the full test.

Not in front of a lab machine right now, but it seems that running under
'qemu-mips -cpu P5600' is sufficient to force it into MIPS4 support.

Actually on my debian/jessie64 VM (what I use for initial testing before
sitting in front of a lab machine), it looks like MIPS4 is the default, as I see
large numbers of movz instructions in the libc code.
