### ISSUE TITLE
Deadline for Compiler

### ISSUE THREAD

**Issue by JB515** [LangProc/langproc_2015_cw#8]
The timeline in the readme gives the compiler deadline as 26th March (following the pattern of submission every other Friday), but the Blackboard deadline is given as the 25th. Which is correct?

**Comment by m8pple** [comment]
The deadline is Fri 25th march, as given in the text of the readme and blackboard.

When creating the figure it looks like I added 8 rather than 7 to get to the
non-existent Fri 26th.

I'll update the figure to say Fri 25th of March.
